// Keeps BUILD_FROM_SCRATCH.md complete: it embeds every file of the project (Part II) and the tiny script that writes them
// out again (the bootstrap at the top). Run it after ANY change to the project, then commit both.
//   node scripts/build-spec.mjs             rewrite the generated parts of BUILD_FROM_SCRATCH.md
//   node scripts/build-spec.mjs --check     exit 1 (and say why) when the file is out of date
// Which files: everything git tracks (so `git add` new files first), except package-lock.json and BUILD_FROM_SCRATCH.md itself.
// package.json is embedded with EXACT dependency versions (taken from package-lock.json) so a fresh `npm install` cannot drift.
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { extname } from 'node:path'

const SPEC = 'BUILD_FROM_SCRATCH.md'
const SKIP = new Set([SPEC, 'package-lock.json'])
const BINARY_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.ico', '.icns', '.jar', '.jks', '.woff', '.woff2', '.ttf', '.zip'])
const LANG = { '.ts': 'typescript', '.tsx': 'tsx', '.js': 'javascript', '.mjs': 'javascript', '.cjs': 'javascript', '.json': 'json', '.yml': 'yaml', '.yaml': 'yaml', '.md': 'markdown', '.java': 'java', '.xml': 'xml', '.gradle': 'groovy', '.html': 'html', '.css': 'css', '.ps1': 'powershell', '.sh': 'bash', '.svg': 'xml', '.properties': 'properties' }

const check = process.argv.includes('--check')
const tracked = execFileSync('git', ['ls-files', '-z'], { encoding: 'utf8', maxBuffer: 1 << 28 }).split('\0').filter(Boolean)

/** Order of the files in Part II: configuration first, then the code in the order it is built. */
const rank = (p) => {
  const order = ['.gitignore', 'package.json', 'tsconfig', 'electron.vite', 'vitest', 'eslint', 'electron-builder', 'capacitor', 'vite.android']
  if (!p.includes('/')) {
    const k = order.findIndex((o) => p.startsWith(o))
    return 100 + (k < 0 ? 50 : k)
  }
  const groups = ['.github/', '.claude/', 'scripts/', 'build/', 'src/shared/', 'src/main/', 'src/preload/', 'src/renderer/', 'test/', 'docs/', 'android/']
  const g = groups.findIndex((x) => p.startsWith(x))
  return 200 + (g < 0 ? 99 : g) * 10
}
const files = tracked.filter((p) => !SKIP.has(p)).sort((a, b) => rank(a) - rank(b) || (a < b ? -1 : 1))

const fenceFor = (text) => '`'.repeat(Math.max(3, ...[...text.matchAll(/`+/g)].map((m) => m[0].length + 1)))
const utf8 = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true })

function pinned(json) {
  const pkg = JSON.parse(json)
  const lock = JSON.parse(readFileSync('package-lock.json', 'utf8'))
  for (const group of ['dependencies', 'devDependencies']) {
    for (const name of Object.keys(pkg[group] ?? {})) {
      const v = lock.packages?.[`node_modules/${name}`]?.version
      if (v) pkg[group][name] = v
    }
  }
  return JSON.stringify(pkg, null, 2) + '\n'
}

function block(path) {
  const buf = readFileSync(path)
  const ext = extname(path).toLowerCase()
  let text = null
  if (!BINARY_EXT.has(ext) && !buf.includes(0)) {
    try {
      text = utf8.decode(buf)
    } catch {
      text = null
    }
  }
  let crlf = false
  if (text !== null && text.includes('\r')) {
    // Windows line ends are allowed when EVERY line has them (flag "crlf"): the block itself is stored with LF
    if (/\r(?!\n)/.test(text) || /(^|[^\r])\n/.test(text)) throw new Error(`${path} mixes line endings; make them all LF or all CRLF`)
    crlf = true
    text = text.replace(/\r\n/g, '\n')
  }
  if (text === null) {
    const b64 = buf.toString('base64').match(/.{1,100}/g) ?? []
    return `#### FILE (base64): ${path}\n\`\`\`base64\n${b64.join('\n')}\n\`\`\``
  }
  if (path === 'package.json') text = pinned(text)
  const eol = text.endsWith('\n')
  const body = eol ? text.slice(0, -1) : text
  const fence = fenceFor(body)
  const flags = [crlf ? 'crlf' : '', eol ? '' : 'no-eol'].filter(Boolean).join(',')
  return `#### FILE${flags ? ` (${flags})` : ''}: ${path}\n${fence}${LANG[ext] ?? ''}\n${body}${body === '' ? '' : '\n'}${fence}`
}

/** The marker comments are built here, never written out, so this file (which the document embeds) cannot be mistaken for a marker. */
function M(kind, name) {
  return '<!' + '-- ' + kind + ' ' + name
}
const kb = (n) => (n / 1024).toFixed(0)
const index = files.map((p) => `- \`${p}\`  (${kb(readFileSync(p).length)} KB)`).join('\n')
const source = [
  M('BEGIN', 'SOURCE FILES') + ' (generated by scripts/build-spec.mjs: do not edit by hand) -->',
  `The ${files.length} files below are the project. \`extract-spec.mjs\` (the bootstrap at the top of this document) writes them all into a folder.`,
  '',
  '<details><summary>Index of the files</summary>',
  '',
  index,
  '',
  '</details>',
  '',
  ...files.map(block),
  M('END', 'SOURCE FILES') + ' -->'
].join('\n\n')

const extractor = readFileSync('scripts/extract-spec.mjs', 'utf8').replace(/\s+$/, '')
const ef = fenceFor(extractor)
const bootstrap = [M('BEGIN', 'BOOTSTRAP') + ' (generated by scripts/build-spec.mjs) -->', `${ef}javascript`, extractor, ef, M('END', 'BOOTSTRAP') + ' -->'].join('\n')

let md = readFileSync(SPEC, 'utf8').replace(/\r\n/g, '\n')
const swap = (text, begin, end, replacement) => {
  const a = text.indexOf(begin)
  const b = text.lastIndexOf(end)
  if (a < 0 || b < 0 || b < a) throw new Error(`markers ${begin} ... ${end} not found in ${SPEC}`)
  return text.slice(0, a) + replacement + text.slice(b + end.length)
}
md = swap(md, M('BEGIN', 'BOOTSTRAP'), M('END', 'BOOTSTRAP') + ' -->', bootstrap)
md = swap(md, M('BEGIN', 'SOURCE FILES'), M('END', 'SOURCE FILES') + ' -->', source)

if (check) {
  const current = readFileSync(SPEC, 'utf8').replace(/\r\n/g, '\n')
  if (current !== md) {
    console.log(`${SPEC} is out of date: run  node scripts/build-spec.mjs  (after git add of any new file), then commit it`)
    process.exit(1)
  }
  console.log(`${SPEC} is up to date (${files.length} files embedded)`)
} else {
  writeFileSync(SPEC, md)
  console.log(`${SPEC}: ${files.length} files embedded, ${(md.length / 1024).toFixed(0)} KB`)
}
